language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip setuptools
  - pip install pipenv
  - pipenv install --dev
script:
  # note don't need to do 'pipenv run' as it installs inside the virtualenv anyway
  - python -m eel script.py web --onefile --noconsole


