language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      env: EXTRA_PYINSTALLER_REQ="" SCRIPT_PYTHON=python3 NAME_SUFFIX=linux
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: EXTRA_PYINSTALLER_REQ="" SCRIPT_PYTHON="pipenv run python" NAME_SUFFIX=osx
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: EXTRA_PYINSTALLER_REQ="pypiwin32" SCRIPT_PYTHON="pipenv run python" NAME_SUFFIX=win PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
- pip install --upgrade pip setuptools || pip install --user --upgrade pip setuptools
- pip install pipenv || pip install --user pipenv
- pipenv install --dev
- if [ -n $EXTRA_PYINSTALLER_REQ ]; then pipenv install $EXTRA_PYINSTALLER_REQ; fi

script:
# version with onefile
# - python -m eel script.py web --onefile --noconsole --name stratapp
# multifile version in a zip file
- $SCRIPT_PYTHON -m eel script.py web --onefile --noconsole --name stratapp_$NAME_SUFFIX

# - zip -r dist/stratapp dist/stratapp

deploy:
  provider: releases
  api_key:
    secure: nFxvXtKrl+m6V10buqW/v2Dvg1V/2S5Gs6imZ3IaAB1aCU8okLzNWli7rCusC+jI2gwQYGd04ckvmK8nHtAXe/0L9PZ1Wy++/SrOcVXCZyffAaZ3Vqb9zNWrKBq6TINgfqSTKxWzlccant+SZuD8XKwuNOweKEzZlZJL0ct8hGpgjpCvznDGAQxOAxsxpamZ9pK11A9RdnuT0eOi8lJm47E36XCeBVttgRVTDouztXUggB7uiqv7c9wZE7D7rX/xCuvH46o2e1bbl6LUAP6MXzQIov2IeKvDkS3/WLxM6RJJNWtWIFLCkKbi6wpawspOHQIcpj7vSGmW5aJ/GodeT+LrREp8hY/o2j9/PX34U2CkmqrQ1mgDfWClWO0rB9KenoY0A+mRGXbIzh/AY3zvTuQ2czT/d2313EcFLTCdVUyLIwdBoqeo7zKGmWIHVjv4RTScFj/A4TBE9XcLmM7gE+3IqhxH+rtg00JITdhSWPIkpJkK630wYcfXdfSX3vQlA1seJvbL7gISMQHzHr2w/qC91LJhH9Gpd0hOkDZ7By23LAQvvfCsL/deoGmwt37+Rx5tSsjIxDKmnQj70S1/dbXnLcTx6Qr4iN9EL3fDn806MEds54zyNhnlLCLGnluIP6/ig9eBmZicsQhbBHBmn172QXnYnoLz91NpLAXT+fw=
  file: 
    - dist/stratapp_linux
    - dist/stratapp_osx
    - dist/stratapp_win
  skip_cleanup: true
  draft: true
  on:
    repo: sortitionfoundation/stratification-app
