# this is written in TOML - https://github.com/toml-lang/toml

id_column = "nationbuilder_id"
# if true, then no 2 people from the same address will be selected
check_same_address = true
max_attempts = 100
columns_to_keep = [
    "first_name",
    "last_name",
    "email",
    "mobile_number",
    "primary_address1",
    "primary_address2",
    "primary_city",
    "primary_zip",
    "Age"
]
